name: test
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - cartopy
  - click
  - cftime
  - dask
  - pandas
  - pytables
  - numpy
  - scipy
  - netCDF4
  - matplotlib
  - xarray
  - tqdm
  - typing_extensions
  - rasterio
  - geopandas
  - shapely
  - ffmpeg
  - pip
  - make
  - bash_kernel
  - black
  - ipython
  - ipywidgets
  - h5netcdf
  - mypy
  - pytest
  - recommonmark
  - nbsphinx
  - sphinx
  - sphinx_rtd_theme
  - nbval
  - pytest-env
  - pytest-cov
  - pytest-xdist
  - testpath
  - flake8
  - isort
  - pip:
    - sphinxcontrib_github_alt
    - sphinx-execute-code-python3

