name: tintx
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - tintx
  - geopandas
  - hdf5
  - pandoc
  - pip
  - pip:
      - furo
      - sphinx-execute-code-python3
      - sphinxcontrib_github_alt
      - nbsphinx
      - recommonmark
      - sphinx
