name: tintx
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cartopy
  - xarray
  - cftime
  - matplotlib
  - ipython
  - tqdm
  - pip
  - pip:
      - sphinx-execute-code-python3
      - sphinx-rtd-theme
      - sphinxcontrib_github_alt
      - nbsphinx
      - recommonmark
      - sphinx
      - tintx
