name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
        max-parallel: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.10-pip-${{ hashFiles('**/setup.py') }}-${{ hashFiles('.github/dependabot/constraints.txt') }}

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH


    - name: Install dependencies
      run: |
        conda install cartopy
        conda run -n base python3 -m pip install --upgrade pip
        conda run -n base python3 -m pip install -e .[docs,tests] --constraint .github/dependabot/constraints.txt

    - name: Linting
      run: |
       # stop the build if there are Python syntax errors or undefined names
       conda run -n base flake8 src/tintx --count --select=E9,F63,F7,F82 --show-source --statistics
       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
       conda run -n based flake8 src/tintx --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
       conda run -n base black -t py310 --check src/tintx
       conda run -n base mypy --install-types --non-interactive src/tintx

    - name: Test with pytest
      run: |
        conda run -n base python3 -m pytest -v --nbval-lax --current-env --cov=src/tintx --cov-report=xml
      env:
        MPLBACKEND: agg

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
