name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    name: lint and style checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add conda to system path
        run: |
         # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Creating conda environment for python 3.11
        run: |
         conda create -n test -c conda-forge -y python=3.11 ffmpeg pip cartopy make
      - name: Install dependencies
        run: |
          conda run -n test python3 -m pip install -e .[tests]
      - name: Linting the code
        run: |
          conda run -n test make lint
  tests:
    name: tintX tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        max-parallel: 5
        matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add conda to system path
        run: |
         # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Creating conda environment for python ${{ matrix.python-version }}
        run: |
         conda create -n test -c conda-forge -y python=${{matrix.python-version}} ffmpeg pip cartopy make
      - name: Install dependencies
        run: |
          conda run -n test python3 -m pip install -e .[tests,docs]
      - name: Test with pytest
        env:
          MPLBACKEND: agg
          DATA_FILES: ./docs/source/_static/data
        run: |
          conda run -n test make test_coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./report.xml
